spring:
  profiles:
    group:
      "local": "localDB, devPort"
      "dev": "devDB, devPort"
      "prod": "prodDB, prodPort"
    active: ${ACTIVE_PROFILE}
  jwt:
    secret: ${JWT_SECRET}

---

spring:
  config:
    activate:
      on-profile: "localDB"
  datasource:
    url: ${DATASOURCE_URL_LOCAL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---

spring:
  config:
    activate:
      on-profile: "devDB"
  datasource:
    url: ${DATASOURCE_URL_DEV}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          format_sql: true
          show_sql: true
  log:
    config:
      path: ./logs
      filename: app-dev
      maxHistory: 7 # 7일
      totalSizeCap: 1GB # 로그 파일 사이즈

---

spring:
  config:
    activate:
      on-profile: "prodDB"
  datasource:
    url: ${DATASOURCE_URL_PROD}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---

spring:
  config:
    activate:
      on-profile: "devPort"

server:
  port: 9000

---

spring:
  config:
    activate:
      on-profile: "prodPort"

server:
  port: 9001
